---
version: "3.9"
services:
    ultrasinger:
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        stdin_open: true
        tty: true
        container_name: UltraSinger 
        volumes:
            -  ./output:/app/UltraSinger/src/output
        image: rakuri255/ultrasinger:latest
