name: Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (Windows)
      if: matrix.TARGET == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-windows.txt
        #pip install -e .

    - name: Install dependencies (others)
      if: matrix.TARGET != 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linux.txt
        #pip install -e .

    - name: Run pytest
      run: python -m pytest --import-mode=append pytest/
